// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_compute_residuals
NumericVector rcpp_compute_residuals(NumericVector temp_i, double zeta, double slope, double beta_max, NumericVector beta_0, NumericVector alpha, NumericVector log_conc, NumericVector log2_value);
RcppExport SEXP _TPP2D_rcpp_compute_residuals(SEXP temp_iSEXP, SEXP zetaSEXP, SEXP slopeSEXP, SEXP beta_maxSEXP, SEXP beta_0SEXP, SEXP alphaSEXP, SEXP log_concSEXP, SEXP log2_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type temp_i(temp_iSEXP);
    Rcpp::traits::input_parameter< double >::type zeta(zetaSEXP);
    Rcpp::traits::input_parameter< double >::type slope(slopeSEXP);
    Rcpp::traits::input_parameter< double >::type beta_max(beta_maxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_0(beta_0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type log_conc(log_concSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type log2_value(log2_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_compute_residuals(temp_i, zeta, slope, beta_max, beta_0, alpha, log_conc, log2_value));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TPP2D_rcpp_compute_residuals", (DL_FUNC) &_TPP2D_rcpp_compute_residuals, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_TPP2D(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
